server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer_route
          uri: http://localhost:8085
          predicates:
            - Path=/api/customers/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\\{segment}
        - id: billing_route
          uri: http://localhost:8086
          predicates:
            - Path=/api/billing/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\\{segment}
